version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fitnesshub-postgres
    restart: always
    environment:
      POSTGRES_DB: fitnesshub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
